### ISSUE TITLE
打haishi会跳出西狮海壬

### ISSUE THREAD

**Issue by kingyue737** [MarkussLugia/Pboard#14]
‘”还是“是中文里相当高频的词语。每次打'haishi'会默认出现西狮海壬（带海狮的宝可梦其实还有很多，如白海狮、花漾海狮），是否考虑将这个别名去掉？

**Comment by MarkussLugia** [comment]
了解，确实是会造成困扰的缩写，这就去掉

**Comment by MarkussLugia** [comment]
bec581e575801d1cefafbf0645642031d2b58837
