### ISSUE TITLE
win10导入显示文件格式错误或损坏

### ISSUE THREAD

**Issue by kingyue737** [MarkussLugia/Pboard#4]
![image](https://user-images.githubusercontent.com/40021217/147913274-92f71b34-63ed-4754-a947-85808ce850cc.png)

使用的是 release中的 Pboard_allPokemon_MSPinyinWin10PC_1.0.0.dat

**Comment by MarkussLugia** [comment]
应在下方的“添加或编辑自定义短语”中导入文件，而不是自学习词汇库。
请仔细阅读操作指南。
