### ISSUE TITLE
有没有可能添加道具地点的词库呢?

### ISSUE THREAD

**Issue by Snowz666** [MarkussLugia/Pboard#6]

**Comment by MarkussLugia** [comment]
当然可以！如果你感兴趣的话可以整理一下这些词汇，然后提交一个PR！
如果你不熟悉PR等GitHub相关操作的话，也可以在这里（或者在反馈群里）把文件发给我，由我来整合进去就行。

**Comment by MarkussLugia** [comment]
已合并PR，issue可以关闭。感谢！
